fp = open("hello.txt","a")
c = fp.read(5)
b = fp.readline(5)
a = fp.readlines()
d = fp.seek(4)
f = fp.tell()
print("C = ",c)
print("B = ",b)
print("A = ",a)
print("D = ",d)
print("F = ",f)
print(fp.read())
#print(o)
