a,b,c,d = range(7,11)
print("A is =",a)
print("B is =",b)
print("C is =",c)
print("D is =",d)
r ,b  = divmod(c,a)
print('R is =',r)
print('R is =',b)
for x,y in [range(10,12),range(13,15),range(15,17)]:
    print("X is =",x)
    print("Y is =",y)
