from sys import argv
script, filename = argv
print(f"We are going to erase all the content of the file {filename} ")
print("If you do not want that click CTRL+C")
print("Click on return if you want this to happen")
input("?")
print("Opening the file...")
targret = open(filename,"w")
print("Truncating the file. Goodbye!")
targret.truncate()
print("Now I am going to ask you for three lines")
line1 = input("Line #1:")
line2 = input("Line #2:")
line3 = input("Line #3:")
print("I am going to write all data to the file")
targret.write(line1)
targret.write("\n")
targret.write(line2)
targret.write("\n")
targret.write(line3)
targret.write("\n")

print("And finally we close it")
targret.close()
