guests = ["Ahmad","Muhammad","Mustafa","Mahmoud"]
print("More people are coming")
guests.insert(0 , "John")
guests.insert(3,"Adam")
guests.append("Rami")
print(guests)
print("Welcome "+guests[0].title() + " to the dinner")
print("Welcome "+guests[1].title() + " to the dinner")
print("Welcome "+guests[2].title() + " to the dinner")
print("Welcome "+guests[3].title() + " to the dinner")
print("Welcome "+guests[4].title() + " to the dinner")
print("Welcome "+guests[5].title() + " to the dinner")
print("Welcome "+guests[6].title() + " to the dinner")
