locations = ["Istanbul", "Amman", "Amsterdam","London","San Fransisco"]
print(locations)
print(sorted(locations))
print(locations)
locations.reverse()
print(locations)
locations.sort()
print(locations)
locations.sort(reverse=True)
print(locations)
