print ("Hello World")
print ("What is your name?")
myname = input()
print("It is good to meet you  "+ myname+'!')
print("What is the lenght of your name")
print(len(myname))
print()
print ("what is your age")
myage = input()
print ("You will be  "+ str(int(myage)+1)+" in a year")
